#!/usr/bin/env zsh

# Advent of Code 2025 runner script


usage() {
    echo "Usage: ./aoc <command> [args...]"
    echo ""
    echo "Commands:"
    echo "  day <day> [input_file]  - Auto-reload with ghcid"
    echo "  run <day> [input_file]  - Build and run once"
    echo "  install                 - Install to ./bin/"
    echo ""
    echo "Day format: XX (XX = day with two digits)"
    echo "Examples:"
    echo "  ./aoc day 01 input.txt"
    echo "  ./aoc run 12 sample.txt"
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

command="$1"
shift

case "$command" in
    "day")
        if [ $# -eq 0 ]; then
            echo "Usage: ./aoc day <day> [input_file]"
            exit 1
        fi
        
        day="$1"
        input_file="${2:-input.txt}"
        
        echo "Starting ghcid for day $day with input $input_file"
        echo "Press Ctrl+C to exit."
        
        ghcid --command="cabal repl" --run="runDay \"$day\" \"$input_file\""
        ;;
        
    "run")
        cabal run aoc -- "$@"
        ;;
        
    "install")
        cabal install --install-method=copy --installdir=./bin --overwrite-policy=always
        echo "Installed to ./bin/aoc"
        ;;
        
    *)
        echo "Unknown command: $command"
        usage
        exit 1
        ;;
esac