#!/usr/bin/env zsh

# Advent of Code 2025 runner script


usage() {
    echo "Usage: ./aoc <command> [args...]"
    echo ""
    echo "Commands:"
    echo "  day <day> [input_file]  - Auto-reload with ghcid"
    echo "  run <day> [input_file]  - Build and run once"
    echo "  install                 - Install to ./bin/"
    echo ""
    echo "Examples:"
    echo "  ./aoc day 01           # Auto-reload, runs both sample.txt and input.txt"
    echo "  ./aoc day 01 file.txt  # Auto-reload with specific file"
    echo "  ./aoc run 12           # Run once, both sample.txt and input.txt"
    echo "  ./aoc run 12 file.txt  # Run once with specific file"
}

if [ $# -eq 0 ]; then
    usage
    exit 1
fi

command="$1"
shift

case "$command" in
    "day")
        if [ $# -eq 0 ]; then
            echo "Usage: ./aoc day <day> [input_file]"
            exit 1
        fi
        
        day="$1"
        shift
        
        echo "Starting ghcid for day $day"
        echo "Press Ctrl+C to exit."
        
        if [ $# -gt 0 ]; then
            # Pass additional arguments if provided
            ghcid --command="cabal repl" --run=":main $day $1"
        else
            # No additional arguments, let Haskell handle defaults
            ghcid --command="cabal repl" --run=":main $day"
        fi
        ;;
        
    "run")
        cabal run aoc -- "$@"
        ;;
        
    "install")
        cabal install --install-method=copy --installdir=./bin --overwrite-policy=always
        echo "Installed to ./bin/aoc"
        ;;
        
    *)
        echo "Unknown command: $command"
        usage
        exit 1
        ;;
esac